stages:
  - build
  - test

# we are on a shared runner so we
# do not use the Docker socket trick
# but Docker in Docker
services:
  - docker:dind

buildDocker:
  stage: build
  image: docker:stable
  script:
    - docker build -t cicdlab/app:$CI_JOB_ID ./webapp

testInDocker:
  stage: test
  image: cicdlab/app:$CI_JOB_ID
  script:
    - python tests.py
